// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZGFifWbJT2fcWvXUlob1V6-d1FSJDnQ',
    appId: '1:778487701783:web:2136ebcda6efc01b075752',
    messagingSenderId: '778487701783',
    projectId: 'smart-kutubxona',
    authDomain: 'smart-kutubxona.firebaseapp.com',
    storageBucket: 'smart-kutubxona.firebasestorage.app',
    measurementId: 'G-Q525PZ1CMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfYweFk42JbVEUWnTeyveiQS3OpUtdVRU',
    appId: '1:778487701783:android:fc47562680ee436b075752',
    messagingSenderId: '778487701783',
    projectId: 'smart-kutubxona',
    storageBucket: 'smart-kutubxona.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUeIhNY2Z-DZc5j5-ynWpMZR6jn7DFi9k',
    appId: '1:778487701783:ios:6d8fd4cd6d994f2e075752',
    messagingSenderId: '778487701783',
    projectId: 'smart-kutubxona',
    storageBucket: 'smart-kutubxona.firebasestorage.app',
    iosBundleId: 'com.example.smartKutubxona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUeIhNY2Z-DZc5j5-ynWpMZR6jn7DFi9k',
    appId: '1:778487701783:ios:6d8fd4cd6d994f2e075752',
    messagingSenderId: '778487701783',
    projectId: 'smart-kutubxona',
    storageBucket: 'smart-kutubxona.firebasestorage.app',
    iosBundleId: 'com.example.smartKutubxona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvZGFifWbJT2fcWvXUlob1V6-d1FSJDnQ',
    appId: '1:778487701783:web:4abc6d3dd60bff6c075752',
    messagingSenderId: '778487701783',
    projectId: 'smart-kutubxona',
    authDomain: 'smart-kutubxona.firebaseapp.com',
    storageBucket: 'smart-kutubxona.firebasestorage.app',
    measurementId: 'G-2JJX07THTN',
  );
}
